let questions = [

  // =========================
  // DATA FUNDAMENTALS
  // =========================

  {
    numb: 1,
    question: "What is data?",
    answer: "Recorded facts, observations, measurements, or representations",
    options: [
      "Only numerical values",
      "Recorded facts, observations, measurements, or representations",
      "Only text",
      "Only computer programs"
    ]
  },

  {
    numb: 2,
    question: "Data need not be numeric. Which can also represent data?",
    answer: "Images",
    options: ["Only numbers", "Images", "Only equations", "Only tables"]
  },

  {
    numb: 3,
    question: "Which is an example of an entity?",
    answer: "Student",
    options: ["Marks", "Student", "Age", "Percentage"]
  },

  {
    numb: 4,
    question: "An attribute describes:",
    answer: "A property of an entity",
    options: [
      "A programming language",
      "A property of an entity",
      "A database server",
      "A network protocol"
    ]
  },

  {
    numb: 5,
    question: "Which is an attribute of a student?",
    answer: "Roll Number",
    options: ["Student", "University", "Roll Number", "Classroom"]
  },

  {
    numb: 6,
    question: "Which of the following is NOT normally considered a form of data?",
    answer: "Algorithm",
    options: ["Text", "Audio", "Video", "Algorithm"]
  },

  {
    numb: 7,
    question: "Why is data important to organizations?",
    answer: "It supports informed decision-making",
    options: [
      "It eliminates all uncertainty",
      "It supports informed decision-making",
      "It removes the need for employees",
      "It only increases storage"
    ]
  },

  {
    numb: 8,
    question: "Which activity can generate large amounts of data?",
    answer: "Online transactions",
    options: [
      "Online transactions",
      "Only printing",
      "Only typing",
      "Only offline calculation"
    ]
  },

  {
    numb: 9,
    question: "Which statement about raw data is correct?",
    answer: "It may require organization and interpretation to become useful",
    options: [
      "It is always meaningful by itself",
      "It may require organization and interpretation to become useful",
      "It is always error-free",
      "It is always numerical"
    ]
  },

  {
    numb: 10,
    question: "Which is an example of data generated by a hospital?",
    answer: "Patient records",
    options: ["Patient records", "Compiler code", "Network cables", "Operating system"]
  },

  // =========================
  // DIKW
  // =========================

  {
    numb: 11,
    question: "What does DIKW stand for?",
    answer: "Data, Information, Knowledge, Wisdom",
    options: [
      "Data, Information, Knowledge, Wisdom",
      "Data, Internet, Knowledge, Web",
      "Database, Information, Key, Wisdom",
      "Data, Intelligence, Knowledge, Work"
    ]
  },

  {
    numb: 12,
    question: "Which is the first level of the DIKW hierarchy?",
    answer: "Data",
    options: ["Wisdom", "Knowledge", "Information", "Data"]
  },

  {
    numb: 13,
    question: "Organized and contextualized data becomes:",
    answer: "Information",
    options: ["Knowledge", "Information", "Wisdom", "Raw data"]
  },

  {
    numb: 14,
    question: "Knowledge is mainly derived from:",
    answer: "Organized information",
    options: ["Random noise", "Organized information", "Only raw numbers", "Only databases"]
  },

  {
    numb: 15,
    question: "Wisdom represents:",
    answer: "Judicious application of knowledge and experience",
    options: [
      "Raw observations",
      "Judicious application of knowledge and experience",
      "Data storage",
      "Data collection"
    ]
  },

  {
    numb: 16,
    question: "What is the correct DIKW sequence?",
    answer: "Data → Information → Knowledge → Wisdom",
    options: [
      "Knowledge → Data → Information → Wisdom",
      "Data → Information → Knowledge → Wisdom",
      "Wisdom → Data → Knowledge → Information",
      "Information → Wisdom → Data → Knowledge"
    ]
  },

  // =========================
  // DATA QUALITY
  // =========================

  {
    numb: 17,
    question: "Accuracy means:",
    answer: "Closeness of data to the true value",
    options: [
      "Amount of data",
      "Closeness of data to the true value",
      "Number of columns",
      "Frequency of collection"
    ]
  },

  {
    numb: 18,
    question: "Completeness refers to:",
    answer: "Presence of all required data",
    options: [
      "Correctness of values",
      "Presence of all required data",
      "Data visualization",
      "Data storage"
    ]
  },

  {
    numb: 19,
    question: "Data consistency means:",
    answer: "Data should not contain contradictions",
    options: [
      "Data should always be numerical",
      "Data should not contain contradictions",
      "Data must be very large",
      "Data must be collected daily"
    ]
  },

  {
    numb: 20,
    question: "Validity checks whether:",
    answer: "Data follows required rules and constraints",
    options: [
      "Data is visually attractive",
      "Data follows required rules and constraints",
      "Data is large",
      "Data is stored online"
    ]
  },

  {
    numb: 21,
    question: "Timeliness means data should be:",
    answer: "Available and up to date when needed",
    options: [
      "Very large",
      "Available and up to date when needed",
      "Always historical",
      "Only numerical"
    ]
  },

  {
    numb: 22,
    question: "Reliability indicates:",
    answer: "The dependability of data",
    options: [
      "The color of a chart",
      "The dependability of data",
      "The size of a database",
      "The number of columns"
    ]
  },

  {
    numb: 23,
    question: "Uniqueness means:",
    answer: "Records should not be unnecessarily duplicated",
    options: [
      "Every record must be different in every field",
      "Records should not be unnecessarily duplicated",
      "Data must be numerical",
      "Data must be recent"
    ]
  },

  {
    numb: 24,
    question: "Which is an example of inaccurate data?",
    answer: "Recording a customer's actual city as a different city",
    options: [
      "Recording the correct city",
      "Recording a customer's actual city as a different city",
      "Recording all required fields",
      "Using valid dates"
    ]
  },

  {
    numb: 25,
    question: "Which issue directly affects completeness?",
    answer: "Missing values",
    options: ["Missing values", "Correct values", "Valid values", "Unique values"]
  },

  // =========================
  // DATA VALUE & REPRESENTATION
  // =========================

  {
    numb: 26,
    question: "Relevance as a data-value characteristic means:",
    answer: "Data should be useful for the problem being studied",
    options: [
      "Data must be numerical",
      "Data should be useful for the problem being studied",
      "Data must be rare",
      "Data must be old"
    ]
  },

  {
    numb: 27,
    question: "Rarity refers to:",
    answer: "Uncommon or infrequent observations",
    options: [
      "Repeated observations",
      "Uncommon or infrequent observations",
      "Missing observations",
      "Invalid observations"
    ]
  },

  {
    numb: 28,
    question: "Novelty refers to:",
    answer: "New or previously unknown information",
    options: [
      "Duplicate information",
      "New or previously unknown information",
      "Incorrect information",
      "Missing information"
    ]
  },

  {
    numb: 29,
    question: "Which is a characteristic of good data representation?",
    answer: "Clarity",
    options: ["Clarity", "Duplication", "Noise", "Missingness"]
  },

  {
    numb: 30,
    question: "Readability in data representation mainly concerns:",
    answer: "How easily data can be understood",
    options: [
      "How large the database is",
      "How easily data can be understood",
      "How fast data is collected",
      "How rare data is"
    ]
  },

  // =========================
  // DATA TYPES
  // =========================

  {
    numb: 31,
    question: "Structured data are generally organized as:",
    answer: "Rows and columns",
    options: ["Random files", "Rows and columns", "Images", "Audio"]
  },

  {
    numb: 32,
    question: "Which is an example of structured data?",
    answer: "Relational database table",
    options: [
      "Video",
      "Relational database table",
      "Audio recording",
      "Social media image"
    ]
  },

  {
    numb: 33,
    question: "Semi-structured data usually:",
    answer: "Has some organizational structure but no fixed relational schema",
    options: [
      "Has no information",
      "Has some organizational structure but no fixed relational schema",
      "Must be stored in SQL",
      "Must be an image"
    ]
  },

  {
    numb: 34,
    question: "Which is a common example of semi-structured data?",
    answer: "JSON",
    options: ["JSON", "Relational table", "JPEG image", "MP4 video"]
  },

  {
    numb: 35,
    question: "Unstructured data generally has:",
    answer: "No predefined tabular structure",
    options: [
      "A fixed relational schema",
      "No predefined tabular structure",
      "Only numerical values",
      "Only categorical values"
    ]
  },

  {
    numb: 36,
    question: "Which is an example of unstructured data?",
    answer: "Video",
    options: ["SQL table", "Video", "Spreadsheet table", "Relational record"]
  },

  {
    numb: 37,
    question: "Qualitative data are mainly:",
    answer: "Descriptive or categorical",
    options: [
      "Descriptive or categorical",
      "Always continuous",
      "Always numerical",
      "Always binary"
    ]
  },

  {
    numb: 38,
    question: "Which is qualitative data?",
    answer: "Blood Group",
    options: ["Height", "Weight", "Blood Group", "Income"]
  },

  {
    numb: 39,
    question: "Quantitative data are:",
    answer: "Numerical and suitable for mathematical operations",
    options: [
      "Only textual",
      "Numerical and suitable for mathematical operations",
      "Only categorical",
      "Only visual"
    ]
  },

  {
    numb: 40,
    question: "Which is quantitative data?",
    answer: "Income",
    options: ["Blood group", "Department", "Income", "Gender"]
  },

  {
    numb: 41,
    question: "Discrete data are generally:",
    answer: "Countable values",
    options: [
      "Countable values",
      "Only text values",
      "Always continuous",
      "Always categorical"
    ]
  },

  {
    numb: 42,
    question: "Number of employees in a company is:",
    answer: "Discrete data",
    options: ["Continuous data", "Discrete data", "Unstructured data", "Nominal data"]
  },

  {
    numb: 43,
    question: "Height is normally considered:",
    answer: "Continuous data",
    options: ["Discrete data", "Continuous data", "Nominal data", "Binary data"]
  },

  // =========================
  // MEASUREMENT SCALES
  // =========================

  {
    numb: 44,
    question: "Which scale contains categories without an inherent order?",
    answer: "Nominal",
    options: ["Nominal", "Ordinal", "Interval", "Ratio"]
  },

  {
    numb: 45,
    question: "Which scale represents ordered categories?",
    answer: "Ordinal",
    options: ["Nominal", "Ordinal", "Interval", "Ratio"]
  },

  {
    numb: 46,
    question: "Which scale has equal intervals but no true zero?",
    answer: "Interval",
    options: ["Nominal", "Ordinal", "Interval", "Ratio"]
  },

  {
    numb: 47,
    question: "Which scale has both equal intervals and a true zero?",
    answer: "Ratio",
    options: ["Nominal", "Ordinal", "Interval", "Ratio"]
  },

  {
    numb: 48,
    question: "Temperature measured in Celsius is generally:",
    answer: "Interval data",
    options: ["Nominal", "Ordinal", "Interval", "Ratio"]
  },

  {
    numb: 49,
    question: "Height is an example of:",
    answer: "Ratio data",
    options: ["Nominal", "Ordinal", "Interval", "Ratio"]
  },

  {
    numb: 50,
    question: "A customer satisfaction level such as Poor, Good, Excellent is:",
    answer: "Ordinal",
    options: ["Nominal", "Ordinal", "Interval", "Ratio"]
  },

  // =========================
  // SCIENCE
  // =========================

  {
    numb: 51,
    question: "The word 'Science' originates from which Latin word?",
    answer: "Scientia",
    options: ["Scientia", "Datum", "Datae", "Scient"]
  },

  {
    numb: 52,
    question: "Science is a systematic process of acquiring knowledge through:",
    answer: "Observation, experimentation, analysis, and reasoning",
    options: [
      "Guessing only",
      "Observation, experimentation, analysis, and reasoning",
      "Programming only",
      "Memorization only"
    ]
  },

  {
    numb: 53,
    question: "Which is the first step of the scientific method?",
    answer: "Observation",
    options: ["Conclusion", "Observation", "Experimentation", "Analysis"]
  },

  {
    numb: 54,
    question: "After identifying a problem, the scientific method generally involves:",
    answer: "Hypothesis formulation",
    options: [
      "Database creation",
      "Hypothesis formulation",
      "Model deployment",
      "Data visualization"
    ]
  },

  {
    numb: 55,
    question: "Which branch includes Computer Science and Data Science?",
    answer: "Computational Sciences",
    options: [
      "Natural Sciences",
      "Social Sciences",
      "Computational Sciences",
      "Medical Sciences"
    ]
  },

  // =========================
  // DATA SCIENCE
  // =========================

  {
    numb: 56,
    question: "Data Science is best described as:",
    answer: "An interdisciplinary field",
    options: [
      "Only a programming language",
      "An interdisciplinary field",
      "Only database administration",
      "Only statistics"
    ]
  },

  {
    numb: 57,
    question: "Which combination represents the three major pillars of Data Science?",
    answer: "Mathematics & Statistics, Computer Science & AI, Domain Knowledge",
    options: [
      "HTML, CSS, JavaScript",
      "Mathematics & Statistics, Computer Science & AI, Domain Knowledge",
      "Networking, Hardware, OS",
      "Accounting, Marketing, Sales"
    ]
  },

  {
    numb: 58,
    question: "Data Science combines statistics, mathematics, computer science and:",
    answer: "Domain knowledge",
    options: ["Networking", "Domain knowledge", "Hardware", "Operating systems"]
  },

  {
    numb: 59,
    question: "A data-driven approach means decisions are based on:",
    answer: "Evidence obtained from data",
    options: [
      "Personal guesses",
      "Evidence obtained from data",
      "Random selection",
      "Only intuition"
    ]
  },

  {
    numb: 60,
    question: "Problem-oriented Data Science mainly focuses on:",
    answer: "Solving real-world problems",
    options: [
      "Increasing database size",
      "Solving real-world problems",
      "Writing code without purpose",
      "Collecting data without analysis"
    ]
  },

  {
    numb: 61,
    question: "The predictive characteristic of Data Science means:",
    answer: "Using data to forecast future outcomes",
    options: [
      "Deleting old data",
      "Using data to forecast future outcomes",
      "Only displaying reports",
      "Only collecting data"
    ]
  },

  {
    numb: 62,
    question: "Scalability in Data Science refers to the ability to:",
    answer: "Handle large and complex datasets",
    options: [
      "Use only small datasets",
      "Handle large and complex datasets",
      "Avoid databases",
      "Avoid computation"
    ]
  },

  {
    numb: 63,
    question: "Which question can Data Science answer?",
    answer: "What is likely to happen next?",
    options: [
      "Only what is the file name?",
      "What is likely to happen next?",
      "Only what is the password?",
      "Only what is the computer model?"
    ]
  },

  // =========================
  // MATHEMATICS & STATISTICS
  // =========================

  {
    numb: 64,
    question: "Probability measures the:",
    answer: "Likelihood of an event occurring",
    options: [
      "Size of a database",
      "Likelihood of an event occurring",
      "Number of columns",
      "Number of files"
    ]
  },

  {
    numb: 65,
    question: "Why is probability important in Data Science?",
    answer: "It helps deal with uncertainty",
    options: [
      "It removes all uncertainty",
      "It helps deal with uncertainty",
      "It replaces data",
      "It creates databases"
    ]
  },

  {
    numb: 66,
    question: "Statistics mainly deals with:",
    answer: "Collecting, analyzing, interpreting, and summarizing data",
    options: [
      "Only programming",
      "Collecting, analyzing, interpreting, and summarizing data",
      "Only storage",
      "Only visualization"
    ]
  },

  {
    numb: 67,
    question: "Which is a measure of central tendency?",
    answer: "Mean",
    options: ["Mean", "Range", "Variance", "Standard deviation"]
  },

  {
    numb: 68,
    question: "Which measure represents the middle value after sorting data?",
    answer: "Median",
    options: ["Mean", "Median", "Variance", "Range"]
  },

  {
    numb: 69,
    question: "Which measure represents the most frequently occurring value?",
    answer: "Mode",
    options: ["Mean", "Median", "Mode", "Variance"]
  },

  {
    numb: 70,
    question: "Standard deviation measures:",
    answer: "Variation or spread in data",
    options: [
      "Number of records",
      "Variation or spread in data",
      "Number of categories",
      "Data type"
    ]
  },

  {
    numb: 71,
    question: "Descriptive statistics primarily:",
    answer: "Summarizes observed data",
    options: [
      "Predicts every future value",
      "Summarizes observed data",
      "Creates databases",
      "Collects sensor data"
    ]
  },

  {
    numb: 72,
    question: "Inferential statistics is used to:",
    answer: "Draw conclusions about a population from samples",
    options: [
      "Only store data",
      "Draw conclusions about a population from samples",
      "Only create charts",
      "Only remove duplicates"
    ]
  },

  {
    numb: 73,
    question: "Hypothesis testing belongs to:",
    answer: "Inferential statistics",
    options: [
      "Descriptive statistics",
      "Inferential statistics",
      "Data storage",
      "Data acquisition"
    ]
  },

  {
    numb: 74,
    question: "A/B testing is mainly used to:",
    answer: "Compare alternatives using data",
    options: [
      "Store files",
      "Compare alternatives using data",
      "Create databases",
      "Remove missing values"
    ]
  },

  {
    numb: 75,
    question: "Linear algebra in Data Science heavily uses:",
    answer: "Vectors and matrices",
    options: ["HTML and CSS", "Vectors and matrices", "SQL tables only", "Web pages"]
  },

  {
    numb: 76,
    question: "Calculus is important in machine learning mainly for:",
    answer: "Optimization",
    options: ["File storage", "Optimization", "Data entry", "Web scraping"]
  },

  {
    numb: 77,
    question: "Gradient Descent is an example of:",
    answer: "An optimization technique",
    options: [
      "Data acquisition technique",
      "An optimization technique",
      "Database technology",
      "Visualization library"
    ]
  },

  // =========================
  // AI & MACHINE LEARNING
  // =========================

  {
    numb: 78,
    question: "Machine Learning is a subset of:",
    answer: "Artificial Intelligence",
    options: ["Databases", "Artificial Intelligence", "Networking", "Statistics only"]
  },

  {
    numb: 79,
    question: "Machine Learning primarily learns patterns from:",
    answer: "Data",
    options: ["Only source code", "Data", "Only hardware", "Only databases"]
  },

  {
    numb: 80,
    question: "Supervised learning requires:",
    answer: "Labeled data",
    options: ["Only unlabeled data", "Labeled data", "No data", "Only text"]
  },

  {
    numb: 81,
    question: "Which is an example of supervised learning?",
    answer: "Spam classification",
    options: [
      "Spam classification",
      "Customer clustering",
      "Dimensionality reduction",
      "Unsupervised segmentation"
    ]
  },

  {
    numb: 82,
    question: "Which is commonly used for supervised regression?",
    answer: "Linear Regression",
    options: ["K-Means", "Linear Regression", "PCA", "DBSCAN"]
  },

  {
    numb: 83,
    question: "Unsupervised learning generally works with:",
    answer: "Unlabeled data",
    options: ["Only labeled data", "Unlabeled data", "No data", "Only target variables"]
  },

  {
    numb: 84,
    question: "Customer segmentation is commonly associated with:",
    answer: "Unsupervised learning",
    options: [
      "Supervised learning",
      "Unsupervised learning",
      "Regression only",
      "Data cleaning"
    ]
  },

  {
    numb: 85,
    question: "Which algorithm is commonly used for clustering?",
    answer: "K-Means",
    options: ["Linear Regression", "K-Means", "Logistic Regression", "Decision Tree"]
  },

  {
    numb: 86,
    question: "Reinforcement learning uses:",
    answer: "Rewards and penalties",
    options: [
      "Only labeled datasets",
      "Rewards and penalties",
      "Only SQL queries",
      "Only missing values"
    ]
  },

  {
    numb: 87,
    question: "Game-playing AI is an example of:",
    answer: "Reinforcement learning application",
    options: [
      "Reinforcement learning application",
      "CSV processing",
      "Database normalization",
      "Data cleaning"
    ]
  },

  // =========================
  // DATA SOURCES & ACQUISITION
  // =========================

  {
    numb: 88,
    question: "Which is a common source of Data Science data?",
    answer: "Databases",
    options: ["Databases", "Only compilers", "Only monitors", "Only keyboards"]
  },

  {
    numb: 89,
    question: "Which source can continuously generate sensor readings?",
    answer: "IoT devices",
    options: ["IoT devices", "Text editors", "Printers only", "Compilers"]
  },

  {
    numb: 90,
    question: "Web scraping is used to collect data from:",
    answer: "Websites",
    options: ["RAM", "Websites", "CPU registers", "Operating systems"]
  },

  {
    numb: 91,
    question: "REST APIs can be used for:",
    answer: "Accessing data from online services",
    options: [
      "Accessing data from online services",
      "Only creating databases",
      "Only formatting text",
      "Only compiling code"
    ]
  },

  {
    numb: 92,
    question: "Which can be a secondary data source?",
    answer: "Government report",
    options: [
      "Your newly conducted survey",
      "Government report",
      "Your own experiment",
      "Your own interview"
    ]
  },

  {
    numb: 93,
    question: "Primary data are:",
    answer: "Collected directly for a specific purpose",
    options: [
      "Always historical",
      "Collected directly for a specific purpose",
      "Always downloaded",
      "Always public"
    ]
  },

  {
    numb: 94,
    question: "Which is an example of primary data collection?",
    answer: "Conducting a survey",
    options: [
      "Using an old government report",
      "Conducting a survey",
      "Downloading a published dataset",
      "Using a research paper"
    ]
  },

  // =========================
  // CSV
  // =========================

  {
    numb: 95,
    question: "Which Pandas function reads a CSV file?",
    answer: "pd.read_csv()",
    options: ["pd.read_csv()", "pd.csv_read()", "pd.open_csv()", "pd.load_csv()"]
  },

  {
    numb: 96,
    question: "What does pd.read_csv() usually return?",
    answer: "A Pandas DataFrame",
    options: ["A list only", "A Pandas DataFrame", "A string only", "A database"]
  },

  {
    numb: 97,
    question: "Which function displays the first five records of a DataFrame?",
    answer: "df.head()",
    options: ["df.first()", "df.head()", "df.start()", "df.top()"]
  },

  {
    numb: 98,
    question: "Which function displays the last records of a DataFrame?",
    answer: "df.tail()",
    options: ["df.last()", "df.tail()", "df.bottom()", "df.end()"]
  },

  {
    numb: 99,
    question: "What does df.shape provide?",
    answer: "Number of rows and columns",
    options: [
      "Only column names",
      "Number of rows and columns",
      "Only data types",
      "Only missing values"
    ]
  },

  {
    numb: 100,
    question: "Which property returns column names?",
    answer: "df.columns",
    options: ["df.names", "df.columns", "df.fields", "df.headers()"]
  },

  {
    numb: 101,
    question: "Which property shows the data types of columns?",
    answer: "df.dtypes",
    options: ["df.types", "df.dtypes", "df.datatypes()", "df.kind"]
  },

  {
    numb: 102,
    question: "Which method gives general information about a DataFrame?",
    answer: "df.info()",
    options: ["df.details()", "df.info()", "df.describe_data()", "df.summary_info()"]
  },

  {
    numb: 103,
    question: "Which expression is commonly used to check missing values column-wise?",
    answer: "df.isnull().sum()",
    options: [
      "df.missing()",
      "df.isnull().sum()",
      "df.null()",
      "df.empty()"
    ]
  },

  {
    numb: 104,
    question: "Which parameter selects specific columns while reading a CSV?",
    answer: "usecols",
    options: ["columnsOnly", "usecols", "select", "fields"]
  },

  {
    numb: 105,
    question: "Which parameter specifies the separator in pd.read_csv()?",
    answer: "sep",
    options: ["separator", "sep", "splitter", "delimiterOnly"]
  },

  {
    numb: 106,
    question: "Which parameter can convert a date column while reading CSV data?",
    answer: "parse_dates",
    options: ["date_convert", "parse_dates", "datetime", "convert_dates"]
  },

  {
    numb: 107,
    question: "Which argument is used when a CSV file has no header row?",
    answer: "header=None",
    options: ["header=None", "noheader=True", "header=FalseOnly", "columns=None"]
  },

  {
    numb: 108,
    question: "Which parameter helps process a very large CSV in portions?",
    answer: "chunksize",
    options: ["pagesize", "chunksize", "rowsize", "batchfile"]
  },

  {
    numb: 109,
    question: "Which Python module provides basic CSV processing?",
    answer: "csv",
    options: ["csv", "pandas_csv", "datatable", "tabular"]
  },

  {
    numb: 110,
    question: "For general Data Science CSV analysis, which is usually preferred?",
    answer: "Pandas",
    options: ["Pandas", "Only csv module", "Only text editor", "Only Excel"]
  },

  // =========================
  // JSON
  // =========================

  {
    numb: 111,
    question: "Which Pandas function reads JSON data?",
    answer: "pd.read_json()",
    options: ["pd.read_json()", "pd.json_read()", "pd.open_json()", "pd.load_json()"]
  },

  {
    numb: 112,
    question: "Which Python function reads JSON from a file?",
    answer: "json.load()",
    options: ["json.load()", "json.read()", "json.open()", "json.file()"]
  },

  {
    numb: 113,
    question: "Which method converts an API response into JSON/Python data?",
    answer: "response.json()",
    options: [
      "response.json()",
      "response.data()",
      "response.parse()",
      "response.load()"
    ]
  },

  {
    numb: 114,
    question: "Which function converts structured data into a DataFrame?",
    answer: "pd.DataFrame()",
    options: [
      "pd.DataFrame()",
      "pd.Table()",
      "pd.Structure()",
      "pd.CreateData()"
    ]
  },

  {
    numb: 115,
    question: "Which function is useful for flattening nested JSON?",
    answer: "pd.json_normalize()",
    options: [
      "pd.json_normalize()",
      "pd.flatten_json()",
      "pd.normalize_json()",
      "pd.json_flat()"
    ]
  },

  // =========================
  // DATA CLEANING & NOISE
  // =========================

  {
    numb: 116,
    question: "What is noise in data?",
    answer: "Random errors, irrelevant information, or meaningless variations",
    options: [
      "Only useful information",
      "Random errors, irrelevant information, or meaningless variations",
      "Only duplicate records",
      "Only missing values"
    ]
  },

  {
    numb: 117,
    question: "In Y = X + ε, what does ε represent?",
    answer: "Noise",
    options: ["True signal", "Noise", "Input", "Output"]
  },

  {
    numb: 118,
    question: "Which can be an example of sensor noise?",
    answer: "An abnormal sensor reading caused by malfunction",
    options: [
      "A valid measurement",
      "An abnormal sensor reading caused by malfunction",
      "A correctly stored value",
      "A verified observation"
    ]
  },

  {
    numb: 119,
    question: "Which problem can noisy data cause in Machine Learning?",
    answer: "Poor model generalization",
    options: [
      "Guaranteed perfect accuracy",
      "Poor model generalization",
      "Automatic data validation",
      "Reduced storage requirement"
    ]
  },

  {
    numb: 120,
    question: "Which technique smooths numerical data using groups of values?",
    answer: "Binning",
    options: ["Binning", "Joining", "Indexing", "Encoding"]
  },

  {
    numb: 121,
    question: "Which technique is commonly used to smooth time-series data?",
    answer: "Moving average",
    options: ["Moving average", "SQL JOIN", "JSON parsing", "Encoding"]
  },

  {
    numb: 122,
    question: "Which method is commonly used to identify extreme observations?",
    answer: "Outlier detection",
    options: ["Outlier detection", "Data encoding", "Data acquisition", "Sorting only"]
  },

  {
    numb: 123,
    question: "Which technique removes repeated records?",
    answer: "Duplicate removal",
    options: ["Duplicate removal", "Normalization", "Aggregation", "Discretization"]
  },

  {
    numb: 124,
    question: "Which technique fills missing values?",
    answer: "Missing-value imputation",
    options: [
      "Missing-value imputation",
      "Data visualization",
      "Data integration",
      "Sorting"
    ]
  },

  {
    numb: 125,
    question: "Which filter can be used for noise removal?",
    answer: "Median filter",
    options: ["Median filter", "SQL filter", "HTML filter", "CSV filter"]
  },

  {
    numb: 126,
    question: "Which filter is specifically mentioned for signal/image noise removal?",
    answer: "Kalman filter",
    options: ["Kalman filter", "SQL filter", "CSV filter", "JSON filter"]
  },

  {
    numb: 127,
    question: "Which Pandas method removes duplicate records?",
    answer: "drop_duplicates()",
    options: ["remove_duplicates()", "drop_duplicates()", "delete_duplicates()", "unique_remove()"]
  },

  {
    numb: 128,
    question: "Which Pandas method can replace missing values?",
    answer: "fillna()",
    options: ["fillna()", "missing()", "replaceMissing()", "nullfill()"]
  },

  // =========================
  // DATA TRANSFORMATION
  // =========================

  {
    numb: 129,
    question: "What is data transformation?",
    answer: "Converting data into another useful format or representation",
    options: [
      "Deleting all data",
      "Converting data into another useful format or representation",
      "Only collecting data",
      "Only visualizing data"
    ]
  },

  {
    numb: 130,
    question: "Which is the correct preprocessing sequence mentioned in the module?",
    answer: "Collection → Cleaning → Integration → Transformation → Analysis",
    options: [
      "Analysis → Collection → Cleaning → Transformation → Integration",
      "Collection → Cleaning → Integration → Transformation → Analysis",
      "Transformation → Collection → Analysis → Cleaning → Integration",
      "Cleaning → Analysis → Collection → Integration → Transformation"
    ]
  },

  {
    numb: 131,
    question: "Normalization usually rescales numerical data to:",
    answer: "A specific range, commonly 0 to 1",
    options: [
      "Only -100 to 100",
      "A specific range, commonly 0 to 1",
      "Only 1 to 10",
      "Only 10 to 100"
    ]
  },

  {
    numb: 132,
    question: "Which formula is associated with Z-score standardization?",
    answer: "z = (x - μ) / σ",
    options: [
      "z = x + μ + σ",
      "z = (x - μ) / σ",
      "z = x × μ × σ",
      "z = μ / (x + σ)"
    ]
  },

  {
    numb: 133,
    question: "Aggregation means:",
    answer: "Combining multiple records into a summary",
    options: [
      "Deleting records",
      "Combining multiple records into a summary",
      "Adding noise",
      "Converting numbers to text"
    ]
  },

  {
    numb: 134,
    question: "Which Pandas operation is commonly used for aggregation by category?",
    answer: "groupby()",
    options: ["groupby()", "splitby()", "aggregateRowsOnly()", "category()"]
  },

  {
    numb: 135,
    question: "Discretization converts:",
    answer: "Continuous values into categories",
    options: [
      "Categories into images",
      "Continuous values into categories",
      "Text into audio",
      "Databases into files"
    ]
  },

  {
    numb: 136,
    question: "Which Pandas function is used for binning continuous values into categories?",
    answer: "pd.cut()",
    options: ["pd.cut()", "pd.bin()", "pd.category()", "pd.discretize()"]
  },

  {
    numb: 137,
    question: "Encoding is used to convert:",
    answer: "Categorical data into numerical representation",
    options: [
      "Numerical data into images",
      "Categorical data into numerical representation",
      "Audio into databases",
      "Tables into websites"
    ]
  },

  {
    numb: 138,
    question: "Why is data transformation useful for Machine Learning?",
    answer: "It can improve the suitability and performance of algorithms",
    options: [
      "It removes the need for data",
      "It can improve the suitability and performance of algorithms",
      "It guarantees perfect predictions",
      "It eliminates all errors automatically"
    ]
  },

  // =========================
  // DATA SCIENCE LIFECYCLE
  // =========================

  {
    numb: 139,
    question: "What is the first stage of the Data Science Lifecycle?",
    answer: "Problem Definition",
    options: ["Data Collection", "Problem Definition", "EDA", "Deployment"]
  },

  {
    numb: 140,
    question: "Why is problem definition important?",
    answer: "A poorly defined problem can lead to an unsuccessful project",
    options: [
      "It increases database size",
      "A poorly defined problem can lead to an unsuccessful project",
      "It removes the need for data",
      "It guarantees model accuracy"
    ]
  },

  {
    numb: 141,
    question: "Which is a source mentioned for data collection in the lifecycle?",
    answer: "IoT devices",
    options: ["IoT devices", "Only compilers", "Only operating systems", "Only printers"]
  },

  {
    numb: 142,
    question: "Data preparation may include:",
    answer: "Cleaning, integration, transformation, and reduction",
    options: [
      "Only visualization",
      "Cleaning, integration, transformation, and reduction",
      "Only deployment",
      "Only reporting"
    ]
  },

  {
    numb: 143,
    question: "Which lifecycle stage identifies patterns, outliers, and relationships?",
    answer: "Exploratory Data Analysis",
    options: [
      "Deployment",
      "Exploratory Data Analysis",
      "Data Collection",
      "Monitoring"
    ]
  },

  {
    numb: 144,
    question: "Which is an activity of EDA?",
    answer: "Identifying outliers",
    options: [
      "Identifying outliers",
      "Deploying an application",
      "Managing cloud infrastructure",
      "Writing database drivers"
    ]
  },

  {
    numb: 145,
    question: "Which stage develops regression, classification, or clustering models?",
    answer: "Model Building",
    options: ["Model Building", "Data Collection", "Deployment", "Monitoring"]
  },

  {
    numb: 146,
    question: "Model Evaluation checks whether a model is:",
    answer: "Accurate, reliable, and suitable for the objective",
    options: [
      "Only large",
      "Accurate, reliable, and suitable for the objective",
      "Only fast",
      "Only visually attractive"
    ]
  },

  {
    numb: 147,
    question: "What happens during Deployment?",
    answer: "The developed solution is implemented in a real-world system",
    options: [
      "Raw data is collected",
      "The developed solution is implemented in a real-world system",
      "Only missing values are removed",
      "Only statistics are calculated"
    ]
  },

  {
    numb: 148,
    question: "Why is model monitoring necessary?",
    answer: "Data and environments can change over time",
    options: [
      "Models never change",
      "Data and environments can change over time",
      "It increases missing values",
      "It removes the need for evaluation"
    ]
  },

  // =========================
  // DATA SCIENCE ROLES
  // =========================

  {
    numb: 149,
    question: "Which role primarily develops predictive models and extracts insights from data?",
    answer: "Data Scientist",
    options: ["Data Analyst", "Data Scientist", "Data Engineer", "Database Administrator"]
  },

  {
    numb: 150,
    question: "Which role primarily designs data pipelines and data infrastructure?",
    answer: "Data Engineer",
    options: ["Data Analyst", "Data Scientist", "Data Engineer", "UI Developer"]
  }

];